\documentclass{article}

\begin{document}
\section*{Two-factor ANOVA with interaction - frequentist}

<<>>=
library(HSAUR3)
data("weightgain",package="HSAUR3")
str(weightgain)

weightgain
@

<<>>=
boxplot(weightgain$weightgain~weightgain$type+weightgain$source)
@

Just to see what reordering the 'by' variables gives

<<>>=
boxplot(weightgain$weightgain~weightgain$source+weightgain$type)
@


Frequentist two-way ANOVA with interaction: 

Predicting weightgain from:
\begin{itemize}
\item Amount of protein in their diet:  two levels, high or low
\item Source of protein: two levels, beef or cereal
\end{itemize}

<<>>=
frequentist_aov = aov(weightgain$weightgain~weightgain$source*weightgain$type)

summary(frequentist_aov)

round(coef(frequentist_aov),3)

tapply(weightgain$weightgain,weightgain$source*weightgain$type,mean)
@

<<>>=
ones = rep(1,nrow(weightgain))
sd(weightgain$weightgain)                                      #sdev
summary(lm(weightgain$weightgain~ones-1))
sum(residuals(lm(weightgain$weightgain~ones-1))^2)             #mean-only rss
summary(lm(weightgain~source,data=weightgain))                 #one-way ANOVA with source
sum(residuals(lm(weightgain~source,data=weightgain))^2)        #rss
summary(lm(weightgain~type,data=weightgain))                   #one-way ANOVA with type
sum(residuals(lm(weightgain~type,data=weightgain))^2)          #rss
summary(lm(weightgain~source+type,data=weightgain))            #two-way ANOVA no interaction
sum(residuals(lm(weightgain~source+type,data=weightgain))^2)   #rss
summary(lm(weightgain~source*type,data=weightgain))            #two-way ANOVA interaction
sum(residuals(lm(weightgain~source*type,data=weightgain))^2)   #rss
@
\end{document}